name: hair_salon_booking
description: Hair salon booking app converted from React Native to Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  share_plus: ^7.2.2
  url_launcher: ^6.1.14
  lottie: ^2.6.0

  # UI Components
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  
  # Navigation
  go_router: ^10.0.0
  
  # State Management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.1.1
  
  # Network
  http: ^1.1.0
  dio: ^5.1.2
  
  # Utils
  flutter_native_splash: ^2.3.1
  image_picker: ^1.0.0
  flutter_secure_storage: ^8.0.0
  country_picker: ^2.0.20
  table_calendar: ^3.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/slide1.jpg
    - assets/slide2.jpg
    - assets/slide3.jpg
    - assets/slide4.jpg
    - assets/slide5.jpg
    - assets/splash_screen_logo.png
    - assets/points_banner_bg.png
    - assets/logo_long.png
    - assets/icons/
    - assets/images/
    - assets/users/
    - assets/services/
    - assets/walk_img_1.png
    - assets/walk_img_2.png
    - assets/walk_img_3.png
    - assets/ic_km.png
    - assets/ic_vi.png
    - assets/ic_us.png


